// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// // import "./globals.css";
// import { inter } from '@/app/ui/fonts';
// import '@/app/ui/global.css'

// // const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//        <body className={`${inter.className} antialiased`}></body>
//      {/* // <body className={inter.className}>{children}</body> */}
//     </html>
//   );
// }

import '@/app/ui/global.css';
import { inter } from '@/app/ui/fonts';
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}